# global.toml is a special file for define global resources
# And look up from Resource.find(resource_name)


[mysqlconnection.mysqlconnection]
host="localhost"
port=3306
user="root"
passwd="root"
database="shanghai"
charset="utf8"


[redis.redis]
host="127.0.0.1"
port=6379


[logger.global]
filename="abc.log"
path="C:/scada/logs"


# Global variables!
[vars]
host="45.32.113.2"
print_exception = 1
dc_device_id=60
