
[main]
name = "labr.realtime"

# 每个30秒, 00秒(归一化时间)后的5秒尝试发送数据
triggers = ["every-hour 00:05", "every-hour 05:05", "every-hour 10:05", "every-hour 15:05", "every-hour 20:05", "every-hour 25:05", "every-hour 30:05", "every-hour 35:05", "every-hour 40:05", "every-hour 45:05", "every-hour 50:05", "every-hour 55:05"]

require = ["labr.sub.toml"]

[vars]
offset_seconds = 305
logger = "me"

[logger.me]
path="D:/scada/logs/labr/{$month}"
filename="labr-{$date}.log"


# action.main 是一个执行序列的第一个action
[action.main]
type = "mysql_exec"
mysqlconnection="mysqlconnection"
sql = "select * from labr_rec where time=from_unixtime({@@trigger_time} - {@@offset_seconds});"
next = "transform"
return = "result_set"
exit_at = "len({@result_set}) == 0"
logto = "{@@logger}"
loglevel = 1




