
[main]
name = "emd.realtime"

# 每个30秒, 00秒(归一化时间)后的5秒尝试发送数据
triggers = ["every-minute 05", "every-minute 35"]

require = ["emd.sub.toml"]

[vars]
offset_seconds = 65
logger = "me"

[logger.me]
path="C:/Users/cloverdc003/log/emd/{$month}"
filename="emd-{$date}.log"


# action.main 是一个执行序列的第一个action
[action.main]
type = "mysql_exec"
mysqlconnection="mysqlconnection"
sql = "select * from dianci where unix_timestamp(datetime) > {@@trigger_time} - {@@offset_seconds} and status=0;"
next = "transform"
return = "result_set"
exit_at = "len({@result_set}) == 0"
logto = "{@@logger}"
loglevel = 1




