

[action.transform]
type = "resultset_to_form"
key_value_attributes = [
    ["electric", "{@result_set.@i.EF}"],
    ["temperature", "{@result_set.@i.Temp}"],
    ["humidity", "{@result_set.@i.Hum}"],
    ["dataTime", "{@result_set.@i.datetime|unixtime}"]
    ]
param0 = "result_set"
return = "form"
logto = "{@@logger}"
next = "post"

[action.post]
type = "http_post"
url = "http://{$host}:1024/d/send/{$emd_device_id}"
param0 = "form"
next = ""